# Generated by Django 4.0.5 on 2022-06-10 15:37

from django.db import migrations, models


def set_flag_to_true(apps, schema_editor):
    """
    Sets the PDF flag to True for all users
    """

    Submission = apps.get_model('submission', 'SubmissionStarter')
    Submission.objects.all().update(pdf_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionstarter',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(
                choices=[(2, 'Bundesverband'), (3, 'User'), (-1, 'Unbekannt')], default=3
            ),
        ),
        migrations.RunPython(set_flag_to_true),
    ]
