# Generated by Django 4.0.5 on 2022-08-14 09:06

from django.db import migrations, models


def update_categories(apps, schema_editor):
    """
    The category field is not a choice field anymore, but a regular text field.

    -> Read the options for the current category field and update the category field
    :param apps:
    :param schema_editor:
    :return:
    """
    Submission = apps.get_model("submission", "SubmissionInternational")
    for submission in Submission.objects.all():
        submission.category = submission.get_category_display()
        submission.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_submissionstarter_pdf_sent_alter_userprofile_type'),
    ]

    operations = [

        migrations.AlterField(
            model_name='submissionstarter',
            name='category',
            field=models.CharField(choices=[('1', 'Bikini-Fitness Klasse I'), ('19', 'Bikini-Fitness Klasse II'), ('20', 'Bikini-Fitness Klasse III'), ('21', 'Frauen Wellness Klasse'), ('2', 'Frauen Fitness-Figur Klasse I'), ('22', 'Frauen Fitness-Figur Klasse II'), ('4', 'Frauen Physique'), ('6', 'Classic-Bodybuilding Klasse I'), ('23', 'Classic-Bodybuilding Klasse II'), ('30', 'Classic Physique'), ('7', 'Paare'), ('31', 'Fit Pairs'), ('8', 'Männer Physique Klassse I'), ('24', 'Männer Physique Klasse II'), ('25', 'Männer Physique Klasse III'), ('11', 'Muscular-Physique'), ('26', 'Männer Klasse I'), ('27', 'Männer Klasse II'), ('28', 'Männer Klasse III'), ('29', 'Männer Klasse IV'), ('30', 'Männer Klasse V')], max_length=2, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='submissionstarter',
            name='terms_and_conditions',
            field=models.BooleanField(verbose_name='Hiermit erkläre ich mich mit den Regeln des DBFV e.V.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Hiermit erkläre ich mich mit den Regeln des DBFV e.V.'),
        ),

        # International submissions
        migrations.AlterField(
            model_name='submissioninternational',
            name='category',
            field=models.CharField(
                choices=[('1', 'Jugend-Bikini-Fitness'), ('2', 'Jugend-Mens Physique'),
                         ('3', 'Jugend-Bodybuilding'), ('4', 'Junioren-Bikini-Fitness'),
                         ('5', 'Junioren-Mens Physique'), ('6', 'Junioren-Bodybuilding'),
                         ('23', 'Junioren-Classic Bodybuilding'),
                         ('21', 'Junioren-Frauen Fitness Figur'),
                         ('22', 'Junioren-Frauen Physique'), ('7', 'Frauen-Bikini-Fitness'),
                         ('25', 'Frauen-Wellness'), ('8', 'Frauen-Fitness-Figur'),
                         ('9', 'Frauen-Physique'), ('10', 'Paare'), ('11', 'Handicappt/Wheelchair'),
                         ('12', 'Classic Bodybuilding'), ('24', 'Classic Physique'),
                         ('13', 'Männer Physique'), ('24', 'Männer Muscular Physique'),
                         ('14', 'Männer Bodybuilding'), ('15', 'Masters-Männer BB'),
                         ('16', 'Masters-Männer Classic BB'), ('17', 'Masters-Männer Physique'),
                         ('18', 'Masters-Frauen Physique'), ('19', 'Masters-Frauen Bikini Fitness'),
                         ('20', 'Masters-Frauen Figur')], max_length=100, verbose_name='Kategorie'),
        ),
        migrations.RunPython(update_categories, noop),
        migrations.AlterField(
            model_name='submissioninternational',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategorie'),
        ),
    ]
