# Generated by Django 4.0.7 on 2022-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_alter_submissioninternational_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiongym',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissioninternational',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionjudge',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
    ]
