# Generated by Django 5.1.15 on 2026-08-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('write_allowed', models.BooleanField(default=False, help_text='Erlaubt POST/PUT/PATCH/DELETE. Ohne Haken nur Lesezugriff.', verbose_name='Schreibzugriff erlaubt')),
                ('allowed_ips', models.CharField(blank=True, default='', help_text='Kommagetrennte IPs oder CIDR-Bereiche (z. B. "203.0.113.5, 198.51.100.0/24"). Leer = keine IP-Einschränkung.', max_length=255, verbose_name='Erlaubte IPs')),
                ('sensitive_access', models.BooleanField(default=False, help_text='Erlaubt Zugriff auf personen-/finanzbezogene Ressourcen (Bankkonten, Benutzerprofile, Rohanträge, interne Modelle). Ohne Haken nur Stammdaten und Lizenz-Endpoints.', verbose_name='Zugriff auf sensible Daten')),
            ],
            options={
                'verbose_name': 'API-Key',
                'verbose_name_plural': 'API-Keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
